"""primera migracion

Revision ID: d88c6c0ee60e
Revises: 
Create Date: 2026-03-13 09:43:46.579624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd88c6c0ee60e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('apaterno',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('amaterno',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=False)
        batch_op.alter_column('amaterno',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('apaterno',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
